{{- if not (eq .Values.poiesis.auth.type "dummy") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poiesis.auth.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "poiesis.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.poiesis.auth.oidc.clientSecret | quote }}
{{- end }}
