{{- include "poiesis.validateStorageBackend" . -}}
{{- if .Values.poiesis.externalDependencies.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poiesis.s3.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "poiesis.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.poiesis.externalDependencies.s3.auth.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.poiesis.externalDependencies.s3.auth.secretKey | quote }}
  AWS_REGION: {{ .Values.poiesis.externalDependencies.s3.region | quote }}
{{- end }}
