---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - python -m pip install uv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install --system .

sphinx:
  configuration: docs/source/conf.py
...
