---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.13.0'
  jobs:
    post_create_environment:
      - python -m pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs

sphinx:
  configuration: docs/source/conf.py
...
