---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

rules:
  truthy:
    ignore:
      - .github/**/*.yaml
  document-start:
    level: error
  line-length:
    ignore:
      - poiesis/api/tes/spec/**/*.yaml
