---
name: Vulnerability test

on:
  push:
    branches:
      - main
  pull_request:
    branches: "**"
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at 12:00 PM UTC

jobs:
  code-vulnerabilities:
    name: Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Harden-Runner
        uses: step-security/harden-runner@v2.10.2

      - name: Set up environment
        uses: ./.github/actions/setup/uv
        with:
          os: ${{ job.os }}
          uv-sync-args: "--only-group vulnerability"

      - name: Check code vulnerabilities with bandit
        run: uv run bandit -c pyproject.toml -r poiesis/

  dependency-vulnerabilities:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Harden-Runner
        uses: step-security/harden-runner@v2.10.2

      - name: Set up environment
        uses: ./.github/actions/setup/uv
        with:
          os: ${{ job.os }}
          uv-sync-args: "--only-group vulnerability"

      - name: Check dependency vulnerabilities with safety
        run: uv run safety check --full-report
...
